### ISSUE TITLE
Firmware

### ISSUE THREAD

**Issue by LemaruX** [bigtreetech/BIGTREETECH-SKR-E3-DIP-V1.0#1]
Please release the uncompiled firmware so we can edit settings and compile for ourselves. Thanks.

**Comment by bjoernwedi** [comment]
Need to change the steppers too

**Comment by Promite2501** [comment]
I think this is meant to be more for their how to PDFs and basic info.  If you want to compile from scratch its is highly recommended to start with the main marlin branch of 2.0. 
[https://github.com/MarlinFirmware/Marlin/tree/bugfix-2.0.x](url)

**Comment by LemaruX** [comment]
Yeah, I'd always use latest vanilla marlin anyway. Just past experiences with my other printers have proven that often they set custom values in their own version of marlin which would be nice to copy over to the original marlin source.

**Comment by claudiusa** [comment]
Bigtreetech released the uncompiled Marlin firmware with board pins configuration today.

**Comment by thisiskeithb** [comment]
It should be in the main Marlin repo soon: https://github.com/MarlinFirmware/Marlin/pull/14638

**Comment by TheZoker** [comment]
@LemaruX I guess you can close this issue, since everything is in the repo

**Comment by oldman4U** [comment]
@thinkyhead (Please close this ticket due to inactivity)

Thank you

1st try;-)
