### ISSUE TITLE
Noisy X motor with SKR marlin 2.0.7.2 release

### ISSUE THREAD

**Issue by Grayfox2005** [bigtreetech/BIGTREETECH-SKR-E3-DIP-V1.0#102]
I just installed the latest firmware from this board and noticed my X axis motor has a scratchy noise like something is rubbing but its coming out of the motor. It was fine with the previous release, I couldn't hear any of the motors. Seems funny it just affects the X. I disabled hybrid threshold because that wasn't enabled in the previous release and that was no help. It sounds like a critter in the ceiling scratching around lol. Just wondered if there is something else I could try to quiet it?

**Comment by Grayfox2005** [comment]
Actually it could be all the motors but only the x seems prominent.

**Comment by oldman4U** [comment]
Which drivers with which setting?

Most likely a Marlin TMC issue.

**Comment by Grayfox2005** [comment]
TMC2209 drivers same settings as the earlier version of Marlin. I put the old one back in and it was definitely gone so its something somewhere in the latest. Just waiting for others to chime in their results.

**Comment by oldman4U** [comment]
Marlin often includes new version of the TMC library. I would recommend to
compile your own firmware, which allows to change the libraries  used.

Grant <notifications@github.com> schrieb am Mo. 14. Dez. 2020 um 21:14:

**Comment by Grayfox2005** [comment]
Thanks I'll look and see the differences in old vs the new. I always compile my own version because I have much more to my printer than is included in the pre-compiled version. I see they are including a lot more in the latest version in controlling the settings of the board and extra hardware which is nice.

**Comment by oldman4U** [comment]
Great.

Please let me know in case you find something.

Happy printing

Grant <notifications@github.com> schrieb am Mo. 14. Dez. 2020 um 21:36:

**Comment by Grayfox2005** [comment]
Guess I'll close this. It's been a long time with no other complaints so it must be an issue on my end.
