### ISSUE TITLE
SKR 1.4 dead or sleepy...

### ISSUE THREAD

**Issue by sawcio** [bigtreetech/BIGTREETECH-SKR-E3-DIP-V1.0#106]
Hello, I've got an issue with my new SKR V1.4 (non Turbo) with LPC1768 onboard, my board died (or fell into a coma) just after next flashing marlin, and the same time I've also connected an mossfeet for HB, so I'm not sure what coud happend. Mossfet works fine with MKS genL. Board Lights up only red light, dosen't grab firmware.bin from microsd, also cant connect via stlinkv2  and also tried 
 UART using GadgetAngel instructions, but looks like board give me an Voltage but no communication. It is possible that micro sd was broken and crashed bootloader? Microsd delivered with board crashed (windows doesn't se it) after few flashing operaqtions but next one worked fine (but it's also cheap one) i didn't use better microsd because I use an octoprint with usb connected ssd drive so there is no need to use it on working printer.

I'm not sure about "reset pin" because as I read the SKR 1.4 dosent have one onboard and I shoud do an shortage to ground from resistor in upper right corner of an LPC1768. What should stlink-Utility show if "reset pin" was not correctly connected?

**Comment by oldman4U** [comment]
This is the wrong repository. Please close here and open a new ticket in the correct repository.
