### ISSUE TITLE
During print suddenly twice the size

### ISSUE THREAD

**Issue by Ofloo** [bigtreetech/BIGTREETECH-SKR-E3-DIP-V1.0#14]
While printing with TMC2208 i hear a crack while it's printing the first layer and suddenly it's printing twice the size, .. again turn of the printer restart everything, and suddenly everything goes back to normal.

**Comment by oldman4U** [comment]
Hello Ofloo.

Seems this ticket has not been used for a while, could you please close it.

Thank you

**Comment by oldman4U** [comment]
@bigtreetech Could you please close this unneeded ticket. Thank you

**Comment by Ofloo** [comment]
Closed it like 3 times already
