### ISSUE TITLE
SKR E3 Dip Firmware

### ISSUE THREAD

**Issue by YanksFan70** [bigtreetech/BIGTREETECH-SKR-E3-DIP-V1.0#28]

**Comment by YanksFan70** [comment]
Does the firmware only get saved to microsd card?

**Comment by lococnc** [comment]
Yes, copy the .bin file to your sd card and boot. It will automatically flash.

**Comment by oldman4U** [comment]
Hello YanksFan70.

Seems this ticket is not needed anymore, so could you please close it.

Thank you

**Comment by YanksFan70** [comment]
Thanks
