### ISSUE TITLE
Axes are misdirected and run in the opposide way 

### ISSUE THREAD

**Issue by Robin2305** [bigtreetech/BIGTREETECH-SKR-E3-DIP-V1.0#33]
I insalled the firmware for the TMC2208 (chip on bottom ) and try to run it (the firmware was installed and stardet up) then i tryed to move the axis but they are completle mistaken. that means when i want to move the X-axis the Y-axis moved and when i want to move the Y-axis the Z-axis moved (and so on). I definitely pluged the steppermotors in the right possition.

Second issue is that they are running the wrong way - if i go +10mm it moved -10mm.

Does anybody have the same problems or does anybody know the solution fore my problems ?

**Comment by chaoticchoas** [comment]
I would suggest quickly check your axis wiring to make sure that it is correct. Then you can try the other tmc2208 firmware (chip on top). If you are still having trouble with the axis moving in the wrong direction or the wrong axis moving then just build your own version of marlin 2.0.x bugfix and you should be able to fix it there.

**Comment by Mesmer88** [comment]
What printer do you have?
I experienced the same on Ender 5 and had to use these settings in Marlin:

#define INVERT_X_DIR true
#define INVERT_Y_DIR true
#define INVERT_Z_DIR false

#define X_HOME_DIR -1
#define Y_HOME_DIR -1
#define Z_HOME_DIR -1

#define USE_XMIN_PLUG
#define USE_YMIN_PLUG
#define USE_ZMIN_PLUG

**Comment by oldman4U** [comment]
Hello Robin2305.

Seems this ticket has not been used for a while, so could you please close it.

Thank you

**Comment by oldman4U** [comment]
@bigtreetech Could you please close this unneeded ticket. Thank you

**Comment by oldman4U** [comment]
Please help the community and close the ticket once you do not need it anymore. Thank you

**Comment by oldman4U** [comment]
Please help the community and close the ticket once you do not need it anymore. Thank you
