### ISSUE TITLE
How to Store settings 

### ISSUE THREAD

**Issue by Robin2305** [bigtreetech/BIGTREETECH-SKR-E3-DIP-V1.0#34]
I'm running the Bugfix 2.0.x Firmware and i don't know how to Store my settings. Like when im changing the stepps/mm how to Safe this settings that they arent lost when i shut down my printer?

**Comment by Pukington** [comment]
You need to upload a file called eeprom.dat to the sd card and enable #EEPROM_SETTINGS in configuration.h.  Click initiate eeprom on the printer display, and then click save settings.

**Comment by oldman4U** [comment]
Hi @Robin2305 

This information is outdated and therefore wrong. Could you please close this ticket 

Thank you
