### ISSUE TITLE
Program freezes on USB connection and probing problem

### ISSUE THREAD

**Issue by Gerno082** [bigtreetech/BIGTREETECH-SKR-E3-DIP-V1.0#38]
Goodday, I am having trouble with my board
When I connect my computer to the board with a usb cable, the program instantly freezes
After a while of changing the code and reflashing the chip, the chip stopped flashing code from the SD card.  I flashed the bootloader from https://github.com/bigtreetech/BIGTREETECH-SKR-E3-DIP-V1.0/issues/2 which seemed to solve the upload problem.  But later when I tested the auto bed leveling, I found that the leveling stops after the 6th probe point.

I have tried this with two E3 DIP boards (bought together, so probably from the same batch) and I got the same results on both and I hadd to reflash the bootloader on both.  Both boards have the RET6 variant of the chip, I have tried both the 256Kb and 512Kb environments in Marlin and I have tried both the official Marlin 2.0 fork and the Bigtree E3 DIP Marlin 2.0 fork.

Could this be related to a memory issue?

**Comment by oldman4U** [comment]
Hi Gerno082.

Have you been able to fix the reported issue in the meantime?

Which motor drivers are you using, maybe i can send you firmware for testing?!

**Comment by oldman4U** [comment]
@bigtreetech Could you please close this unneeded ticket. Thank you
