### ISSUE TITLE
Bigtreetech Marlin need update

### ISSUE THREAD

**Issue by ICGE6544** [bigtreetech/BIGTREETECH-SKR-E3-DIP-V1.0#42]
Branch BIGTREETECH-SKR-E3-DIP-V1.0/Firmware/Marlin-2.0.x-SKR-E3-DIP/ need to be updated.

It would be nice from a member of Bigtreetech to update the marlin for the SKR mini E3 dip (the one for the skr mini e3 v1 is up to date).
If I compile the actual firmware for the SKR mini E3 dip with Atom and PIO 4.1 it causes a blue screen (brick) on my Ender 3, not the case with the one for mini E3 v1.It is not a problem caused by Platform io version, Marlin package should be updated.
So please update Marlin package for the mini SKR E3 dip, thank you.

**Comment by TheZoker** [comment]
Update is done:
https://github.com/bigtreetech/BIGTREETECH-SKR-E3-DIP-V1.0/commit/37e0af8e8e0d83ef535132595e23c3c7a5338a04

**Comment by oldman4U** [comment]
Hello ICGE6544.

Could you please close this ticket.

Thank you

**Comment by ICGE6544** [comment]
solved
