### ISSUE TITLE
Skr e3 dip Usb not detected.. driver not working

### ISSUE THREAD

**Issue by hopatz** [bigtreetech/BIGTREETECH-SKR-E3-DIP-V1.0#45]
Hi
I try install maple driver from this github but only detected as unknown devices..
Please help

**Comment by oldman4U** [comment]
Hi hopatz.

What would you like to do with the USB port?

 As far as i know you can use it with Printrun and print directly from Cura, but you will not be able to see the SD card like a drive of your computer and you will not be able to do firmware updates - again, based on the practical experience i have with this board.

**Comment by hopatz** [comment]
My tmc2130 + skr e3 now working fine
But still got message tmc connection error, i just wanna to diagnostic why its happened

**Comment by oldman4U** [comment]
Hi.

I get the TMC Connection Error as soon as i have the computer connected via USB and Cura v4.4 opened. Having Cura closed the time i start the printer solves the problem.

**Comment by oldman4U** [comment]
Hello hopatz.

Is this issue solved in the meantime or do you need any further help?

**Comment by boz3d** [comment]
Hi, I think you have an wrong mail address I have no issue with the boards! Brboris-------- Ursprüngliche Nachricht --------Von: oldman4U <notifications@github.com>Datum: Mi., 29. Jan. 2020, 10:22An: "bigtreetech/BIGTREETECH-SKR-E3-DIP-V1.0" <BIGTREETECH-SKR-E3-DIP-V1.0@noreply.github.com>Cc: Subscribed <subscribed@noreply.github.com>Betreff: Re: [bigtreetech/BIGTREETECH-SKR-E3-DIP-V1.0] Skr e3 dip Usb not detected.. driver not working (#45)Hello hopatz.
Is this issue solved in the meantime or do you need any further help?

**Comment by oldman4U** [comment]
Hi boz3d.

Not sure why you got my answer, but it was for hopatz, the owned of this ticket.

Sorry.

**Comment by oldman4U** [comment]
@thinkyhead (Please close this ticket due to inactivity)

Thank you
