### ISSUE TITLE
Heated Bed sensors

### ISSUE THREAD

**Issue by Johannesvanhooff** [bigtreetech/BIGTREETECH-SKR-E3-DIP-V1.0#47]
I did build a printer like UM2+, after completing the construction I did try and de steppers without heating up the hotend and or the hotbed. Worked perfectly.
Then I did connect the thermistor to E0 - ptc 1000, code 1047, worked perfectly after the application of autotune pid.
Then I did connect the thermistor (100k - thus code 1) and the heater for the bed, to the connector indicated: screen result was bed temp -14ºC. The thermistor at the plug by the board was 100k, thus failure somewhere else. I did decide to plug the cable to the connector of the 2nd hotend, without any modification of the software; and the result was that the system works: but slowly and does not reach temp >60ºC-
The instruction for the auto pid gives the failure "PID autotune failed!Bad extruder numer". Changing E-1, for E1, E2 or E-2 gives the same result.
I did not touch the file pins_BIGTREE_SKR_V1.3h
The pid part for the bed is:

//===========================================================================
//====================== PID > Bed Temperature Control ======================
//===========================================================================

/**
 * PID Bed Heating
 *
 * If this option is enabled set PID constants below.
 * If this option is disabled, bang-bang will be used and BED_LIMIT_SWITCHING will enable hysteresis.
 *
 * The PID frequency will be the same as the extruder PWM.
 * If PID_dT is the default, and correct for the hardware/configuration, that means 7.689Hz,
 * which is fine for driving a square wave into a resistive load and does not significantly
 * impact FET heating. This also works fine on a Fotek SSR-10DA Solid State Relay into a 250W
 * heater. If your configuration is significantly different than this and you don't understand
 * the issues involved, don't use bed PID until someone else verifies that your hardware works.
 */
#define PIDTEMPBED

//#define BED_LIMIT_SWITCHING

/**
 * Max Bed Power
 * Applies to all forms of bed control (PID, bang-bang, and bang-bang with hysteresis).
 * When set to any value below 255, enables a form of PWM to the bed that acts like a divider
 * so don't use it unless you are OK with PWM on your bed. (See the comment on enabling PIDTEMPBED)
 */
#define MAX_BED_POWER 255 // limits duty cycle to bed; 255=full current

#if ENABLED(PIDTEMPBED)
  //#define MIN_BED_POWER 0
  //#define PID_BED_DEBUG // Sends debug data to the serial port.

  //120V 250W silicone heater into 4mm borosilicate (MendelMax 1.5+)
  //from FOPDT model - kp=.39 Tp=405 Tdead=66, Tc set to 79.2, aggressive factor of .15 (vs .1, 1, 10)
  //#define DEFAULT_bedKp 10.00
  //#define DEFAULT_bedKi .023
  //#define DEFAULT_bedKd 305.4

  //120V 250W silicone heater into 4mm borosilicate (MendelMax 1.5+)
  //from pidautotune
  #define DEFAULT_bedKp 97.1
  #define DEFAULT_bedKi 1.41
  #define DEFAULT_bedKd 1675.16

  // FIND YOUR OWN: "M303 E-1 C8 S90" to run autotune on the bed at 90 degreesC for 8 cycles.
#endif // PIDTEMPBED

What do I wrong?

**Comment by oldman4U** [comment]
Hello Johannesvanhooff.

Seems no-one can help you with the reported issue. Could you please be so kind and close the ticket.

Thank you
