### ISSUE TITLE
TMC2208 UART cannot set mstep

### ISSUE THREAD

**Issue by totti001** [bigtreetech/BIGTREETECH-SKR-E3-DIP-V1.0#48]
Hi,

I've just bought SKR E3 DIP board with tcm2208 v3.0 drivers. I've compiled the latest marlin. My problem is that the Z axis driver is not set as expected. It has mstep value always 8. I've changed the drivers between the slots and the result is same. I've read the status witn m122 v and this is the result:
SENDING:M122 V
		X		Y		Z		E
GCONF		0x00:00:00:C0	0x00:00:00:C0	0x00:00:01:01	0x00:00:00:C0
IHOLD_IRUN	0x00:0A:17:0B	0x00:0A:17:0B	0x00:0A:17:0B	0x00:0A:1C:0E
GSTAT		0x00:00:00:00	0x00:00:00:00	0x00:00:00:00	0x00:00:00:00
IOIN		0x20:00:03:41	0x20:00:03:41	0x20:00:03:41	0x20:00:01:41
TPOWERDOWN	0x00:00:00:80	0x00:00:00:80	0x00:00:00:80	0x00:00:00:80
TSTEP		0x00:0F:FF:FF	0x00:0F:FF:FF	0x00:0F:FF:FF	0x00:0F:FF:FF
TPWMTHRS	0x00:00:00:00	0x00:00:00:00	0x00:00:00:00	0x00:00:00:00
TCOOLTHRS
THIGH
CHOPCONF	0x14:02:82:84	0x14:02:82:84	0x15:02:82:84	0x14:02:82:84
COOLCONF
PWMCONF	0xC8:0D:0E:24	0xC8:0D:0E:24	0xC8:0D:0E:24	0xC8:0D:0E:24
PWM_SCALE	0x00:00:00:0D	0x00:00:00:0D	0x00:00:00:1B	0x00:00:00:10
DRV_STATUS	0xC0:0B:00:00	0xC0:0B:00:00	0xC0:17:00:00	0xC0:0E:00:00

As I can see the gconf is different at the z axis. But I don't know why. Do you have any suggestion?-

Thanks

**Comment by oldman4U** [comment]
Hello totti001.

Seems no-one can help you with the reported issue. Could you please be so kind and close the ticket.

Thank you

**Comment by oldman4U** [comment]
@bigtreetech Could you please close this unneeded ticket. Thank you

**Comment by oldman4U** [comment]
Please help the community and close the ticket once you do not need it anymore. Thank you

**Comment by oldman4U** [comment]
Please help the community and close the ticket once you do not need it anymore. Thank you

**Comment by oldman4U** [comment]
Please help the community and close the ticket once you do not need it anymore. Thank you
