### ISSUE TITLE
Mix tmc5160 spi and tmc2208 uart

### ISSUE THREAD

**Issue by hopatz** [bigtreetech/BIGTREETECH-SKR-E3-DIP-V1.0#49]
Hi,
If my board skr e3 dip v1.0 has 3 tmc2208 uart installed and 1 tmc5160 spi.. what should i do? can i use uart mode at tmc 2208 same time spi also enabled at tmc5160

**Comment by oldman4U** [comment]
Hello hopatz.

Long time no see;-)

Seems no-one can help you with the reported issue. Could you please be so kind and close the ticket.

Thank you
