### ISSUE TITLE
What firmware should I install

### ISSUE THREAD

**Issue by aISergey** [bigtreetech/BIGTREETECH-SKR-E3-DIP-V1.0#54]
Tell me please. I bought an E3 DIP TMC2208 UART. When the printer starts up, it displays the message: "TMC Connection Error". What firmware should I install:
firmware-tmc2208-chip-on-bottom.bin
or
firmware-tmc2208-chip-on-top.bin

**Comment by aISergey** [comment]
On the advice of the seller, I installed firmware-tmc2208-chip-on-bottom.bin and got a blue screen of death.

**Comment by stockHuman** [comment]
After setting your jumpers to UART, flash [this file](https://github.com/bigtreetech/BIGTREETECH-SKR-E3-DIP-V1.0/blob/56bb4e56ac75b802b99a15611351fe062762531f/Firmware/firmware-tmc2208.bin) from pull #57.

**Comment by oldman4U** [comment]
Hello aISergey.

Could you please let us know the status of this ticket.

Thank you

**Comment by aISergey** [comment]
Hello oldman4U!
I'm sorry. The issue can be close, I made the firmware manually from the original Marlin.

**Comment by oldman4U** [comment]
Hi.

Good to hear you could solve the problem!;-)

Unfortunately i can not close it, but only the user which opened it. So could you please close it.

Thank you
