### ISSUE TITLE
SD cart is not present in the menu

### ISSUE THREAD

**Issue by TOMDED** [bigtreetech/BIGTREETECH-SKR-E3-DIP-V1.0#59]
I've just set up the configuration file to TMC 2208 with UART, uncomment manual mesh bed leveling and compiled. Every thing seems to be ok. Printer is moving all axes, homing ok, manual bed leveling ok. But can't find SD cart in the menu. Init Media is not initializing SD cart. Checked SD cart support in configuration files - also uncomment.
https://youtu.be/3FGq2QuHyu4
[Configuration.zip](https://github.com/bigtreetech/BIGTREETECH-SKR-E3-DIP-V1.0/files/4368910/Configuration.zip)

**Comment by Viking117** [comment]
try 
#define SERIAL_PORT -1
#define SERIAL_PORT_2 2

**Comment by BearBroendum** [comment]
@TOMDED . 
I´m having the same issue with my printer. Can not communicate with the board either on sdcard or mini-usb.
Have you come closer to a solution?

**Comment by TOMDED** [comment]
There was a SD card problem. After change the SD card everything went to ok.
