### ISSUE TITLE
E0-STOP labeled as `stallguard` in the instructions. lead to confision

### ISSUE THREAD

**Issue by sl1pkn07** [bigtreetech/BIGTREETECH-SKR-E3-DIP-V1.0#60]
Hi

in the instructions

![Screenshot_20200410_173616](https://user-images.githubusercontent.com/462213/79003070-16e71880-7b52-11ea-99a6-18c608cf705e.png)

but actually is set as runout sensor in marlin

https://github.com/MarlinFirmware/Marlin/blob/0518dec60d0931745efa2812fa388f33d68cfa29/Marlin/src/pins/stm32f1/pins_BTT_SKR_E3_DIP.h#L59-L64

this lead confusion, because `stallguard` is a function for TMC drivers (some models, not all)

greetings

**Comment by MohanMaker** [comment]
Thanks for letting us know. Just fixed the manual and opened a pull request to this repository. You should be able to close this issue now.
