### ISSUE TITLE
power loss recovery

### ISSUE THREAD

**Issue by petrce** [bigtreetech/BIGTREETECH-SKR-E3-DIP-V1.0#66]
looks like power-loss recovery is off or not working by default, is that by design (just trying to find out why)?
I am using firmware-tmc2208.bin
DIP V1.1 with tmc2208

**Comment by MohanMaker** [comment]
Yes, power loss recovery is not enabled in the pre-compiled firmware. If you would like to enable it you can compile your own firmware using the "Marlin-2.0.5_SKR-E3-DIP" files. Make sure to uncomment "#define POWER_LOSS_RECOVERY" and set "#define PLR_ENABLED_DEFAULT" to true.

**Comment by oldman4U** [comment]
Hello petrce.

What is the status of the reported issue?

Please close the ticket if the issue has been fixed in the meantime

Thank you

**Comment by oldman4U** [comment]
@bigtreetech Could you please close this unneeded ticket. Thank you

**Comment by oldman4U** [comment]
Please help the community and close the ticket once you do not need it anymore. Thank you
