### ISSUE TITLE
Cant find software for E3 DIP V1.1

### ISSUE THREAD

**Issue by Pretous** [bigtreetech/BIGTREETECH-SKR-E3-DIP-V1.0#67]
Hello, i know this software work for V1.1 too, but you can add any notification about it. I spent whole day to find that software from V1.0 fit for V1.1

**Comment by MohanMaker** [comment]
Pull request #70 fixes this.

**Comment by txt4nk** [comment]
Pretous, I will compile a firmware for you if you tell me what your setup is (including all mods)

**Comment by slippy3002** [comment]
TXT4NK would you compile a firmware for me?
Ender 3
E3 DIP V1.1
TFT35 v3.0
TMC2209 Drivers
all stock besides that

**Comment by txt4nk** [comment]
Sure, ill compile it tomorrow morning when I get to work.

**Comment by slippy3002** [comment]
Thank you!

**Comment by slippy3002** [comment]
> Sure, ill compile it tomorrow morning when I get to work.

Have you gotten the chance today?

**Comment by txt4nk** [comment]
Im sorry, today turned out to be an absolute circus at work. I'll get it done tomorrow.

**Comment by txt4nk** [comment]
This should do the trick. While you update your board firmware, I would also update the TFT's firmware if you haven't already. Below is a link to BTT's guide on updating firmware, and a link to a zip file with the project files and a pre-compiled firmware binary file for you.

https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware

[Marlin-bugfix-2.0.x_slippy3002.zip](https://github.com/bigtreetech/BIGTREETECH-SKR-E3-DIP-V1.0/files/4925786/Marlin-bugfix-2.0.x_slippy3002.zip)

**Comment by slippy3002** [comment]
txt4nk Thanks!  you are the best!

**Comment by txt4nk** [comment]
No problem

**Comment by slippy3002** [comment]
txt4nk The stepper motors are backwards and there is no jerk...

**Comment by txt4nk** [comment]
I'll reverse the steppers tomorrow. Can you verify if the extruder is reversed please

**Comment by slippy3002** [comment]
Yes the extruder is backwards too

**Comment by txt4nk** [comment]
Give this one a shot.

[Marlin-bugfix-2.0.x_slippy3002.zip](https://github.com/bigtreetech/BIGTREETECH-SKR-E3-DIP-V1.0/files/4942144/Marlin-bugfix-2.0.x_slippy3002.zip)

**Comment by slippy3002** [comment]
Sorry for the late reply.  That worked well.  Thatnk you again!  You should make this available for everyone.

**Comment by txt4nk** [comment]
> Sorry for the late reply. That worked well. Thatnk you again! You should make this available for everyone.

I have added repo's on my github for my personal printers. I will start to do that for these builds that I do for you guys as well, when time permits of course. Hard to find time when I work 70+ hours a week.

**Comment by oldman4U** [comment]
@Pretous 

The reported issue is solved. Please close this ticket.

Thank you

**Comment by oldman4U** [comment]
@bigtreetech

Please close this ticket

**Comment by oldman4U** [comment]
Please help the community and close the ticket once you do not need it anymore. Thank you
