### ISSUE TITLE
Missing Schematic

### ISSUE THREAD

**Issue by danielfmo** [bigtreetech/BIGTREETECH-SKR-E3-DIP-V1.0#7]
Please add Hardware schematic like it exists for other bigtreetech boards.

Example:
https://github.com/bigtreetech/BIGTREETECH-SKR-V1.3/blob/master/hardware/SKR-V1.3-SCH.pdf

Thank you in advance

**Comment by pyunramura** [comment]
Patiently waiting for this as well. Thanks for raising the issue.

**Comment by Ofloo** [comment]
Would like to see it as well.

**Comment by danielfmo** [comment]
Schematic is available as of https://github.com/bigtreetech/BIGTREETECH-SKR-E3-DIP-V1.0/commit/d21d9aa645165ad5e74659796e524c04bc081c24
