### ISSUE TITLE
Question: how to figure out which chip is used on my SKR E3-DIP?

### ISSUE THREAD

**Issue by VijitCoder** [bigtreetech/BIGTREETECH-SKR-E3-DIP-V1.0#80]
From the [readme.md](https://github.com/bigtreetech/BIGTREETECH-SKR-E3-DIP-V1.0/blob/master/Firmware/README.md)

> Note, some SKR E3-DIP boards ship with different chips (RCT6 or RET6)

How to figure out which chip is used on my SKR E3-DIP?

**Comment by ckuethe** [comment]
See https://github.com/bigtreetech/BIGTREETECH-SKR-E3-DIP-V1.0/issues/71#issuecomment-628241209 - it's printed right on the chip

**Comment by VijitCoder** [comment]
Got it. Thanks.

**Comment by VijitCoder** [comment]
I suggest to add this info to readme file.
