### ISSUE TITLE
BLTouch problem.

### ISSUE THREAD

**Issue by pevire** [bigtreetech/BIGTREETECH-SKR-E3-DIP-V1.0#86]
Hello, I've compiled marlin from: BIGTREETECH-SKR-E3-DIP-V1.0/Firmware/Marlin-2.0.5_SKR-E3-DIP/ to use BLTouch.

X and Y homing works fine, but if I do a Z homing, the Y carriage goes to the right (even beyond of the limits making a "crack crack crack" sound) and I get this message:

"READ: Error:!! STOP called because of BLTouch error - restart with M999
READ: Error:Printer stopped due to errors. Fix the error and use M999 to restart. (Temperature is reset. Set it after restarting)"

BlTouch is well connected and it works well with M280. If I compile Marlin without BLtouch, Z homing works well.

Any idea? Thanks.

**Comment by pevire** [comment]
I edit. It is not a problem with BLTouch. Marlin in

**Comment by oldman4U** [comment]
Hi.

I would attach the Marlin files so someone can check them.

**Comment by pevire** [comment]
A problem with drive type. Sorry.
