### ISSUE TITLE
Compile error with fresh everything

### ISSUE THREAD

**Issue by bkrowiak** [bigtreetech/BIGTREETECH-SKR-E3-DIP-V1.0#88]
Coincidentally new install of win10 and everything else is giving me this when I try to compile 2.0.5 for my E3 DIP
All I'm attempting to do is change settings in configuration.h to account for some new hardware. Previous firmware was probably 2.0.0
![Screenshot (2)](https://user-images.githubusercontent.com/58346921/87480725-eead0100-c5fb-11ea-9a12-5c76986614a1.png)

**Comment by oldman4U** [comment]
Hi.

Please try this Marlin version: https://github.com/MarlinFirmware/Marlin/tree/bugfix-2.0.x

and change the environment to "BIGTREE_SKR_PRO in platformio.ini

It it fails the first time, try it a second time

Please let me know

**Comment by bkrowiak** [comment]
It got me through, but I had to change the environment and tool around with library dependencies. Thanks
