### ISSUE TITLE
Thermistors appear linked

### ISSUE THREAD

**Issue by Venares** [bigtreetech/BIGTREETECH-SKR-E3-DIP-V1.0#9]
Both Bed and Nozzle thermistors appear to be linked somehow.
If I raise the temp on the nozzle the bed temp also rises causing thermal runaway.
The same can be seen if raising the bed temp causing the nozzle temp to increase at the same rate.
If one thermostor is unplugged the temp readings dramatically drop for both sensors.

**Comment by oldman4U** [comment]
He.

Have you been able to solve the problem. If so, please close this ticket.

Thank you

**Comment by oldman4U** [comment]
@bigtreetech Could you please close this unneeded ticket. Thank you

**Comment by oldman4U** [comment]
Please help the community and close the ticket once you do not need it anymore. Thank you

**Comment by oldman4U** [comment]
Please help the community and close the ticket once you do not need it anymore. Thank you

**Comment by oldman4U** [comment]
Please help the community and close the ticket once you do not need it anymore. Thank you

**Comment by oldman4U** [comment]
Please help the community and close the ticket once you do not need it anymore. Thank you

**Comment by oldman4U** [comment]
Please help the community and close the ticket once you do not need it anymore. Thank you

**Comment by oldman4U** [comment]
Please help the community and close the ticket once you do not need it anymore. Thank you

**Comment by oldman4U** [comment]
Please help the community and close the ticket once you do not need it anymore. Thank you

**Comment by Venares** [comment]
.
