### ISSUE TITLE
How to connect UPS 1.0 to SKR E3 DIP?

### ISSUE THREAD

**Issue by Meshchankin** [bigtreetech/BIGTREETECH-SKR-E3-DIP-V1.0#93]
Sorry how to connect UPS 1.0 to SKR E3 DIP?
What should I write in #define POWER_LOSS_PIN ???
How to connect it to this main board ?

**Comment by oldman4U** [comment]
Hi. This mainboard is a 1:1 replacement for the original mainboard which does not support the UPS. You will need another mainboard or a display which supports it.

**Comment by Meshchankin** [comment]
> Hi. This mainboard is a 1:1 replacement for the original mainboard which does not support the UPS. You will need another mainboard or a display which supports it.

May be possible to use Filament sensor connector ?

**Comment by oldman4U** [comment]
Hi. 

I use a BLTouch with this board but i am not aware if you can connect anything else to it. I would buy a TFT which supports all the features you would like to use.

**Comment by oldman4U** [comment]
Please help the community and close the ticket once you do not need it anymore. Thank you

**Comment by oldman4U** [comment]
Please help the community and close the ticket once you do not need it anymore. Thank you

**Comment by Meshchankin** [comment]
I have buy this ups because your official dealer at Aliexplress told me
that it will work with SKR E3 DIP.
Please add this information to UPS manual because it's important.
I will close

чт, 1 окт. 2020 г. в 07:45, oldman4U <notifications@github.com>:

**Comment by oldman4U** [comment]
I am not BTT but a user like you. Maybe you would like to ask your question in the Marlin repository because it finally has to work with it.

Bad documentation of all those features is a shame. 

Keeping a ticket open even after months is useless and makes the ticket system unusable.

**Comment by Meshchankin** [comment]
Thank you!

Now I know this but your store doesn't know it.
They promise compatibility with ALL boards.
So please add this information to manual or stay it here.

чт, 1 окт. 2020 г. в 10:10, oldman4U <notifications@github.com>:

**Comment by oldman4U** [comment]
Again. It is not my store, and i have nothing to do with BTT or the dealer.

It is possible that there is a way to attach it and I do not know it, so it would be the best to contact the dealer who promised the compatibility and ask how to connect it. Once you know it, and you want to share what you learned, you could let us know.

This would be great

Thank you

**Comment by oldman4U** [comment]
So have you contacted the dealer and have you got an answer?

Please let me know

**Comment by oldman4U** [comment]
Please help the community and close the ticket once you do not need it anymore. Thank you

**Comment by oldman4U** [comment]
Please help the community and close the ticket once you do not need it anymore. Thank you
